### PR TITLE
a

### PR DESCRIPTION
**Pull request by mimishoal**

### CODE REVIEW

**Comment by mimishoal** [comment]
i wanted to do pr in the last week to the last pr and i couldn't do it
because i don't have the new address from the github
*מייל זה לצרכי עבודה בלבד!!!*


‫בתאריך יום א׳, 28 ביולי 2024 ב-3:46 מאת ‪gemtechd‬‏ <‪
***@***.***‬‏>:‬

**Comment by mimishoal** [comment]
*מייל זה לצרכי עבודה בלבד!!!*
i wanted to do pr in the last week to the last task and i couldn't do it
because i don't have the new address from the github

‫בתאריך יום א׳, 28 ביולי 2024 ב-4:14 מאת ‪Mindy fux‬‏ ***@***.***
‬‏>:‬

**Comment by gemtechd** [comment]
Sorry but it's closed
I can open you again the project for this PR

**Comment by mimishoal** [comment]
ok,thank
and also what with the 2 last tasks that they are in review in not in done?
(about the middleware task if what you have in the github  its not good i
can upload it again (i have it 'and its works good))
what you dont use with these tasks?
thank!
*מייל זה לצרכי עבודה בלבד!!!*


‫בתאריך יום א׳, 28 ביולי 2024 ב-9:51 מאת ‪gemtechd‬‏ <‪
***@***.***‬‏>:‬

**Comment by gemtechd** [comment]
You can upload what you have

**Pull request closed without merging**
